name: Draw.io

on:
  push:
    branches:
      - Master

jobs:
  render_drawio:
    runs-on: ubuntu-latest
    name: Render .drawio files
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_TOKEN }}
    
    - name: Render .drawio files
      uses: docker://ghcr.io/racklet/render-drawio-action:v1
      with:
        formats: 'png'
        sub-dirs: 'docs'
        skip-dirs: '.git'
      id: render
      
    - name: List the rendered files
      run: 'ls -l ${{ steps.render.outputs.rendered-files }}'
    
    - name: Commit the rendered files
      uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actor
        message: 'Automatically render .drawio files'
        add: "${{ steps.render.outputs.rendered-files }}"
      if: "${{ steps.render.outputs.rendered-files != ''}}"
