name: Draw.io

on:
  push:
    branches:
      - Docs

jobs:
  drawio:
    name: Draw.io to PNG
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensures all files are fetched

      - name: Debug - List files in docs folder
        run: ls -R ./docs

      - name: Convert Draw.io diagram to PNG
        uses: Burnett01/actions-drawio@1.2
        with:
          src: "./docs/System Architecture.drawio"
          dest: "./docs/System Architecture.png"
